"""
Slack Bot Backend — Incident Post-Mortem Writer
================================================
Bare minimum Slack slash command bot.

USAGE FLOW:
  User in Slack: /postmortem <incident-json-url>
  Bot fetches JSON, runs PagerDuty importer + agent, replies with post-mortem.

REQUIREMENTS:
    pip install fastapi uvicorn requests openai python-multipart

ENV VARS NEEDED:
    SLACK_SIGNING_SECRET  — from Slack app Basic Information
    API_BASE_URL          — Groq base URL
    MODEL_NAME            — llama-3.1-8b-instant
    HF_TOKEN              — Groq API key

RUN LOCALLY:
    uvicorn slackbot.app:app --port 8000 --reload

EXPOSE PUBLICLY (in another terminal):
    ngrok http 8000

Then paste the ngrok URL into your Slack app's Slash Command Request URL:
    https://abc123.ngrok.io/slack/postmortem
"""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import sys
import time
from pathlib import Path

import requests
from fastapi import FastAPI, Request, BackgroundTasks
from fastapi.responses import JSONResponse, PlainTextResponse

# ─── Reuse existing project code ───
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from tools.pagerduty_importer import import_pagerduty_incident  # noqa: E402

app = FastAPI()

# ─── Config from environment ───
SLACK_SIGNING_SECRET = os.environ.get("SLACK_SIGNING_SECRET", "")
API_BASE_URL = os.environ.get("API_BASE_URL", "https://api.groq.com/openai/v1")
MODEL_NAME = os.environ.get("MODEL_NAME", "llama-3.1-8b-instant")
HF_TOKEN = os.environ.get("HF_TOKEN", "")


# ─── Slack signature verification ───
def verify_slack_signature(request_body: bytes, timestamp: str, signature: str) -> bool:
    """Verify request actually came from Slack."""
    if not SLACK_SIGNING_SECRET:
        print("[WARN] SLACK_SIGNING_SECRET not set — skipping verification")
        return True

    # Reject if timestamp is older than 5 minutes (replay attack protection)
    if abs(time.time() - int(timestamp)) > 300:
        return False

    sig_basestring = f"v0:{timestamp}:{request_body.decode('utf-8')}"
    expected_sig = "v0=" + hmac.new(
        SLACK_SIGNING_SECRET.encode("utf-8"),
        sig_basestring.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()

    return hmac.compare_digest(expected_sig, signature)


# ─── Agent: generate post-mortem from incident JSON ───
def generate_postmortem(scenario: dict) -> str:
    """Run LLM agent against the imported scenario, return formatted post-mortem."""
    from openai import OpenAI

    client = OpenAI(base_url=API_BASE_URL, api_key=HF_TOKEN)

    # Build context for LLM
    alerts = scenario.get("initial_alerts", [])
    slack_thread = scenario.get("slack_thread", [])

    context = f"INCIDENT: {scenario.get('incident_title', 'Unknown')}\n\n"
    context += "ALERTS:\n"
    for a in alerts:
        context += f"  [{a.get('timestamp')}] {a.get('service')} ({a.get('severity')}): {a.get('message')}\n"
    context += "\nSLACK THREAD:\n"
    for s in slack_thread:
        context += f"  [{s.get('timestamp')}] {s.get('author')}: {s.get('text')}\n"

    prompt = f"""You are an SRE writing a post-mortem. Based on this incident data, write a structured post-mortem with these 5 sections: SUMMARY, TIMELINE, ROOT_CAUSE, IMPACT, ACTION_ITEMS.

Use Slack-friendly markdown formatting (bold with *asterisks*, not **double asterisks*).
Be specific — name services, times, and mechanisms. Aim for ~250 words total.

{context}

Write the post-mortem now:"""

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
        max_tokens=600,
    )
    return response.choices[0].message.content


def post_to_slack(response_url: str, text: str, thread_ts: str | None = None):
    """Post a message back to Slack via the response_url from slash command."""
    payload = {
        "response_type": "in_channel",
        "text": text,
    }
    requests.post(response_url, json=payload, timeout=10)


def process_incident_async(response_url: str, incident_url: str):
    """Background task: fetch JSON, run agent, post back to Slack."""
    try:
        # Fetch the JSON
        resp = requests.get(incident_url, timeout=10)
        resp.raise_for_status()
        pagerduty_payload = resp.json()

        # Import → scenario
        scenario = import_pagerduty_incident(pagerduty_payload)

        # Run agent
        postmortem = generate_postmortem(scenario)

        # Format Slack response
        message = (
            f":memo: *Post-Mortem for {scenario.get('incident_id')}*\n"
            f"_{scenario.get('incident_title')}_\n\n"
            f"{postmortem}\n\n"
            f"_Generated by incident-postmortem-writer agent (Llama 3.1 8B)_"
        )

        post_to_slack(response_url, message)

    except Exception as e:
        post_to_slack(
            response_url,
            f":warning: Failed to generate post-mortem: `{type(e).__name__}: {str(e)[:200]}`"
        )


# ─── Routes ───

@app.get("/health")
async def health():
    return {"status": "ok"}


@app.post("/slack/postmortem")
async def slack_postmortem(request: Request, background_tasks: BackgroundTasks):
    """Slack slash command handler. MUST respond within 3 seconds."""
    body = await request.body()

    # Verify it's actually from Slack
    timestamp = request.headers.get("X-Slack-Request-Timestamp", "")
    signature = request.headers.get("X-Slack-Signature", "")
    if not verify_slack_signature(body, timestamp, signature):
        return JSONResponse({"error": "invalid signature"}, status_code=401)

    # Parse form data (Slack sends URL-encoded form, not JSON)
    form = await request.form()
    text = form.get("text", "").strip()
    response_url = form.get("response_url", "")

    # Validate input
    if not text.startswith("http"):
        return JSONResponse({
            "response_type": "ephemeral",
            "text": (
                ":x: *Usage:* `/postmortem <url-to-incident-json>`\n"
                "Example: `/postmortem https://raw.githubusercontent.com/Jeevan2798/incident-postmortem-writer/main/samples/pagerduty/incident_payments_outage.json`"
            ),
        })

    # Acknowledge immediately, then process in background
    background_tasks.add_task(process_incident_async, response_url, text)

    return JSONResponse({
        "response_type": "in_channel",
        "text": f":mag: Generating post-mortem from `{text[:80]}`... (takes ~15-30s)",
    })


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
